export const STARTED_LOADING = "STARTED_LOADING";
export const NEW_PAGE_LOADED = "NEW_PAGE_LOADED";
export const PAGE_SWITCHED = "PAGE_SWITCHED";
export const ROW_PER_PAGE_CHANGED = "ROW_PER_PAGE_CHANGED";
export const SEARCH_TEXT_CHANGED = "SEARCH_TEXT_CHANGED";
export const SEARCH_RESULTS_LOADED = "SEARCH_RESULTS_LOADED";
export const CLEAR_SEARCH_RESULTS = "CLEAR_SEARCH_RESULTS";
